### PR TITLE
Home page test

### PR DESCRIPTION
**Pull request by niamurrell**
Added html from a bootstrap theme.

### CODE REVIEW

**Review by charlenehunter — COMMENTED** [review]
I think we might be able to remove some of the additional fontawesome and bootstrap files

**Comment by charlenehunter** [comment]
I’ll take a look later

**Comment by niamurrell** [comment]
I added another commit to the PR to get rid of all the extra files

**Comment by charlenehunter** [comment]
Awesome! Thanks! I'll get it uploaded :)

**Review by charlenehunter — APPROVED** [review]

**Pull request merged**
